// src/data/badges.js

import {
    FiAward,
    FiStar,
    FiTarget,
    FiHeart,
    FiBookOpen,
    FiTool,
    FiCompass,
    FiCheckCircle,
    FiDroplet,
    FiCpu,
    FiUserCheck,
    FiPackage,
    FiEye,
    FiMapPin,
} from "react-icons/fi";

/**
 * Central badge registry — all badges for the SDG Explorer game
 * Reference in BadgePage, unlockBadge, and all scenes
 */
export const BADGES = [
    {
        key: "first-awareness",
        name: "First Awareness",
        color: "#23C96F",
        Icon: FiAward,
        desc: "You’ve officially been introduced to the SDGs.",
        unlockHint: "Talk to a certain someone in Chapter 1.",
    },
    {
        key: "small-actions-matter",
        name: "Small Actions Matter",
        color: "#23C96F",
        Icon: FiDroplet,
        desc: "Real change starts with small, everyday actions.",
        unlockHint: "Collect trash or interact with environmental objects.",
    },
    {
        key: "sdg-101",
        name: "SDG 101",
        color: "#4B70E2",
        Icon: FiBookOpen,
        desc: "You’ve been formally introduced to the SDGs.",
        unlockHint: "Complete the classroom quiz in Chapter 1.",
    },
    {
        key: "awareness-advocate",
        name: "Awareness Advocate",
        color: "#60A5FA",
        Icon: FiStar,
        desc: "Sustainability exists in ordinary spaces.",
        unlockHint: "Interact with classroom posters or NPCs.",
    },
    {
        key: "on-the-right-track",
        name: "On the Right Track",
        color: "#F59E0B",
        Icon: FiCompass,
        desc: "You’re no longer just aware, you’re moving forward.",
        unlockHint: "Complete Chapter 1 objectives.",
    },
    {
        key: "curious-cat",
        name: "Curious Cat",
        color: "#FD6925",
        Icon: FiTarget,
        desc: "You noticed something unusual about someone lingering around.",
        unlockHint: "Interact with the lingering NPC in Chapter 1 cafeteria.",
    },
    {
        key: "hungry-but-aware",
        name: "Hungry But Aware",
        color: "#FB7185",
        Icon: FiHeart,
        desc: "Sustainability exists even when you’re preoccupied with other needs.",
        unlockHint: "Talk to the cafeteria group while tracking your objectives.",
    },
    {
        key: "first-hand-experience",
        name: "First-Hand Experience",
        color: "#23C96F",
        Icon: FiAward,
        desc: "You didn’t just hear about it, you showed up.",
        unlockHint: "Talk to the food bank organizer in Chapter 2.",
    },
    {
        key: "understanding-the-process",
        name: "Understanding the Process",
        color: "#22D3EE",
        Icon: FiPackage,
        desc: "You learned how the food bank operates behind the scenes.",
        unlockHint: "Collect posters and interact with volunteers at the food bank.",
    },
    {
        key: "reality-check",
        name: "Reality Check",
        color: "#4B70E2",
        Icon: FiEye,
        desc: "You now see where action truly happens.",
        unlockHint: "Observe volunteers outside the food bank.",
    },
    {
        key: "every-role-matters",
        name: "Every Role Matters",
        color: "#60A5FA",
        Icon: FiUserCheck,
        desc: "You realized the impact of collective effort.",
        unlockHint: "Interact with multiple NPCs helping at the food bank street scene.",
    },
    {
        key: "empathy-gained",
        name: "Empathy Gained",
        color: "#FB7185",
        Icon: FiHeart,
        desc: "You now see the impact through a real person.",
        unlockHint: "Talk to the lingering girl and learn her story in Chapter 2.",
    },
    {
        key: "quiet-companion",
        name: "Quiet Companion",
        color: "#FD6925",
        Icon: FiStar,
        desc: "Some support doesn’t need words.",
        unlockHint: "Interact with the cat NPC in Chapter 2.",
    },
    {
        key: "putting-knowledge-to-the-test",
        name: "Putting Knowledge to the Test",
        color: "#4B70E2",
        Icon: FiBookOpen,
        desc: "You completed the SDG quiz after guidance.",
        unlockHint: "Interact with the Sustainable Development Initiatives screen in Chapter 3.",
    },
    {
        key: "guided-by-experience",
        name: "Guided by Experience",
        color: "#23C96F",
        Icon: FiAward,
        desc: "You sought advice instead of guessing your way forward.",
        unlockHint: "Talk to Professor Danny in Chapter 3.",
    },
    {
        key: "composting-basics",
        name: "Composting Basics",
        color: "#22D3EE",
        Icon: FiAward,
        desc: "Waste can be part of the solution.",
        unlockHint: "Interact with the composting table in the greenhouse.",
    },
    {
        key: "climate-in-action",
        name: "Climate in Action",
        color: "#FBBF24",
        Icon: FiMapPin,
        desc: "You learned how everyday actions affect the environment.",
        unlockHint: "Complete dialogue with the gardener about climate action.",
    },
    {
        key: "hands-on-help",
        name: "Hands-On Help",
        color: "#23C96F",
        Icon: FiTool,
        desc: "You learned from someone who leads by example.",
        unlockHint: "Talk to the volunteer at the pond in Chapter 4.",
    },
    {
        key: "leave-it-better",
        name: "Leave It Better",
        color: "#22D3EE",
        Icon: FiTool,
        desc: "You improved a shared space through action.",
        unlockHint: "Complete the pond trash cleanup.",
    },
    {
        key: "greener-commute",
        name: "Greener Commute",
        color: "#4B70E2",
        Icon: FiDroplet,
        desc: "Small transport choices have big impact.",
        unlockHint: "Talk to the bus stop NPC about public transport.",
    },
    {
        key: "everyday-awareness",
        name: "Everyday Awareness",
        color: "#60A5FA",
        Icon: FiEye,
        desc: "Sustainability exists in ordinary spaces.",
        unlockHint: "Inspect the posters at the bus stop.",
    },
];
